"""Grounded generation service (REQUIREMENTS A4-*; ARCHITECTURE §17, §32.1).

Pipeline per chat request::

    retrieved evidence ─▶ confidence gate (§15) ─▶ refusal (code, never model)
                                    │ sufficient
                                    ▼
        grounding prompt (prompt.py) ─▶ LLMProvider ─▶ citation guard (§18)
                                    │
                                    ▼
        validated answer + sources (§19 traceability)

The refusal string is fixed by specification: it is emitted verbatim by code,
never generated by the model, so it can never be paraphrased away. When the
model itself returns the refusal text, the outcome is normalized to the
code-level refusal (``refused=True``) so telemetry and the API stay truthful
about which layer refused. An empty provider response is a provider failure,
never a blank assistant message.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

from app.core.errors import AppError
from app.domain.models import MessageRole
from app.generation.citation_guard import (
    CitationCheck,
    build_sources,
    validate_citations,
)
from app.generation.prompt import build_generation_request
from app.language.models import LanguageCode
from app.language.service import REFUSAL_RESPONSES, answer_instruction
from app.llm.base import ChatMessage, GenerationRequest, LLMProvider
from app.observability.metrics import REFUSALS
from app.retrieval.models import RetrievedEvidence

logger = logging.getLogger(__name__)

#: Required refusal response (REQUIREMENTS A4-012; ARCHITECTURE §15).
#: English form; every supported language's form lives in
#: ``app.language.service.REFUSAL_RESPONSES`` (multilingual support, D-077).
REFUSAL_RESPONSE = "I don't know based on the available source material."

_ENGLISH = LanguageCode.EN


def _refusal_for(language: LanguageCode | None) -> str:
    """Code-controlled refusal in the answer language (never model-made)."""
    return REFUSAL_RESPONSES[language or _ENGLISH]


class EmptyGenerationError(AppError):
    """The provider returned no content for a sufficient-evidence question."""

    status_code = 503
    code = "LLM_EMPTY_RESPONSE"


@dataclass(slots=True)
class GenerationOutcome:
    """Result of one grounded generation call."""

    answer: str
    refused: bool
    citations: CitationCheck = field(default_factory=CitationCheck)
    sources: list[dict[str, object]] = field(default_factory=list)
    model: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None


def _is_refusal_text(answer: str) -> bool:
    """True when the model produced the specification refusal.

    Matches the refusal in ANY supported language (the model may echo the
    translated refusal text, D-077) — the outcome is then normalized to
    the code-controlled refusal of the answer language. The refusal may
    be prefaced with a short hedge ("...therefore: I don't know based on
    the available source material."), so a trailing match counts too.
    """
    stripped = answer.strip()
    for refusal in REFUSAL_RESPONSES.values():
        if stripped == refusal or stripped.endswith(refusal):
            return True
    return False


class GenerationService:
    """Evidence-grounded answering with code-level citation enforcement."""

    def __init__(self, provider: LLMProvider, *, max_attempts: int = 2) -> None:
        self._provider = provider
        self._max_attempts = max_attempts

    async def answer(
        self,
        question: str,
        evidence: RetrievedEvidence,
        history: list[ChatMessage] | None = None,
        *,
        answer_language: LanguageCode | None = None,
    ) -> GenerationOutcome:
        """Generate a grounded, citation-validated answer (or refusal).

        The confidence gate (ARCHITECTURE §15) runs before any LLM call:
        insufficient evidence produces the specification refusal without the
        model seeing the question. Generated answers are sanitized by the
        citation guard; if the guard removed sentences, one regeneration
        attempt is made before accepting the sanitized text.

        ``answer_language`` (D-077) selects the answer language; None means
        English (the pre-multilingual contract, byte-identical prompt). The
        refusal and the language instruction are code-controlled, so the
        language can never weaken grounding, citations, or refusal.
        """
        refusal_text = _refusal_for(answer_language)
        if not evidence.sufficient or (not evidence.results and not evidence.document_hits):
            logger.info(
                "refusing: insufficient evidence",
                extra={
                    "event": "generation_refusal",
                    "reason": "insufficient_evidence",
                    "confidence": round(evidence.confidence, 4),
                },
            )
            REFUSALS.inc()
            return GenerationOutcome(answer=refusal_text, refused=True)

        instruction = (
            answer_instruction(answer_language)
            if answer_language is not None and answer_language != _ENGLISH
            else None
        )
        request = build_generation_request(
            question,
            evidence.results,
            history,
            document_hits=evidence.document_hits,
            answer_language_instruction=instruction,
        )
        check = CitationCheck()
        answer = ""
        model: str | None = None
        prompt_tokens: int | None = None
        completion_tokens: int | None = None
        saw_text = False
        for attempt in range(self._max_attempts):
            result = await self._provider.generate(request)
            model = result.model or model
            prompt_tokens = (result.prompt_tokens or 0) + (prompt_tokens or 0) or None
            completion_tokens = (result.completion_tokens or 0) + (completion_tokens or 0) or None
            if not result.text.strip():
                # An empty completion is a provider failure, not an answer.
                logger.info(
                    "provider returned empty response",
                    extra={"event": "generation_empty_response", "attempt": attempt + 1},
                )
                continue
            saw_text = True
            answer, check = validate_citations(
                result.text, evidence.results, document_hits=evidence.document_hits
            )
            if _is_refusal_text(answer):
                # The model itself refused: normalize to the code-level
                # refusal so refused=true and REFUSALS stay truthful.
                logger.info(
                    "model emitted refusal text; normalizing",
                    extra={"event": "generation_refusal", "reason": "model_emitted"},
                )
                REFUSALS.inc()
                return GenerationOutcome(
                    answer=refusal_text,
                    refused=True,
                    citations=check,
                    model=model,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                )
            if not check.removed_sentences:
                break
            logger.info(
                "citation guard removed sentences; regenerating",
                extra={
                    "event": "citation_guard_regeneration",
                    "attempt": attempt + 1,
                    "removed": len(check.removed_sentences),
                },
            )
            # Regeneration gets the same evidence and rules; append the
            # sanitized prefix as the assistant context so the model does not
            # repeat the removed claim.
            request = GenerationRequest(
                messages=[
                    *request.messages,
                    ChatMessage(role=MessageRole.ASSISTANT, content=answer),
                    ChatMessage(
                        role=MessageRole.USER,
                        content=(
                            "Continue the answer using ONLY the evidence above. "
                            "Do not repeat removed statements; cite every legal "
                            "claim as instructed."
                        ),
                    ),
                ]
            )

        if not saw_text:
            logger.warning("provider produced no content across attempts")
            raise EmptyGenerationError("The generation provider returned an empty response.")

        if not answer.strip():
            # Every sentence was stripped by the guard: nothing grounded
            # survived, so the honest outcome is the specification refusal.
            logger.info(
                "refusing: no grounded sentence survived validation",
                extra={"event": "generation_refusal", "reason": "empty_answer_after_validation"},
            )
            REFUSALS.inc()
            return GenerationOutcome(
                answer=refusal_text,
                refused=True,
                model=model,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
            )

        if not check.valid_citations and not check.cited_document_ids:
            # A non-empty answer with ZERO citations cannot be a grounded
            # legal answer (every legal claim must carry a citation). A
            # model that "complies" with "don't cite the answer" produces
            # exactly this shape — refuse rather than emit uncited law.
            logger.info(
                "refusing: answer carries no citations",
                extra={"event": "generation_refusal", "reason": "no_citations_in_answer"},
            )
            REFUSALS.inc()
            return GenerationOutcome(
                answer=refusal_text,
                refused=True,
                model=model,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
            )

        sources: list[dict[str, object]] = build_sources(evidence.results, check.valid_citations)
        # Document sources are distinguished from statutory authority
        # (A5-012) and emitted only for documents the answer actually cites.
        cited_documents = set(check.cited_document_ids)
        document_sources: list[dict[str, object]] = [
            {
                "source_type": "user_document",
                "citation": (
                    f"[Document {hit.document_id} p.{hit.page_start}]"
                    if hit.page_start
                    else f"[Document {hit.document_id}]"
                ),
                "document_id": hit.document_id,
                "chunk_id": hit.chunk_id,
                "text": hit.text,
                "page_start": hit.page_start,
                "page_end": hit.page_end,
                "source_uri": hit.source_uri,
            }
            for hit in evidence.document_hits
            if hit.document_id in cited_documents
        ]
        for source in sources:
            source["source_type"] = "statute"
        logger.info(
            "generation complete",
            extra={
                "event": "generation_complete",
                "answer_length": len(answer),
                "citations_valid": len(check.valid_citations),
                "citations_invalid": len(check.invalid_citations),
                "citations_irrelevant": len(check.irrelevant_citations),
                "documents_cited": len(cited_documents),
                "model": model,
            },
        )
        return GenerationOutcome(
            answer=answer,
            refused=False,
            citations=check,
            sources=[*sources, *document_sources],
            model=model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
        )
