"""Grounded generation service (REQUIREMENTS A4-*; ARCHITECTURE §17, §32.1).

Pipeline per chat request::

    retrieved evidence ─▶ confidence gate (§15) ─▶ refusal (code, never model)
                                    │ sufficient
                                    ▼
        grounding prompt (prompt.py) ─▶ LLMProvider ─▶ citation guard (§18)
                                    │
                                    ▼
        validated answer + sources (§19 traceability)

The refusal string is fixed by specification: it is emitted verbatim by code,
never generated by the model, so it can never be paraphrased away. When the
model itself returns the refusal text, the outcome is normalized to the
code-level refusal (``refused=True``) so telemetry and the API stay truthful
about which layer refused. An empty provider response is a provider failure,
never a blank assistant message.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field

from app.core.errors import AppError
from app.domain.models import MessageRole
from app.generation.citation_guard import (
    CitationCheck,
    build_sources,
    validate_citations,
)
from app.generation.prompt import build_generation_request
from app.language.models import LanguageCode
from app.language.service import REFUSAL_RESPONSES, answer_instruction
from app.llm.base import ChatMessage, GenerationRequest, LLMProvider
from app.llm.sanitize import is_prompt_echo, sanitize_answer_text
from app.observability.metrics import REFUSALS
from app.retrieval.models import RetrievedEvidence

logger = logging.getLogger(__name__)

#: Required refusal response (REQUIREMENTS A4-012; ARCHITECTURE §15).
#: English form; every supported language's form lives in
#: ``app.language.service.REFUSAL_RESPONSES`` (multilingual support, D-077).
REFUSAL_RESPONSE = "I don't know based on the available source material."

_ENGLISH = LanguageCode.EN

# Contextual refusal reasons (A4-011/A4-012 UX remediation). The pre-LLM
# confidence-gate refusal used to be a single fixed line regardless of WHY
# retrieval failed — a foreign-statute question, an empty session, and a
# low-confidence match all read identically. The retrieval layer already
# explains itself in ``RetrievedEvidence.reasons`` (code-authored English
# constants, never user text); the mappings below turn the strongest
# failure reason into ONE user-facing sentence. Every sentence is a
# code-authored constant — the only interpolated value is the statute name
# the retrieval gate itself isolated from the query with its own Title-case
# regex, so no raw internals or user prose leak into the answer.
#
# Ordering is precedence: foreign statute > session/upload > confidence >
# no match. English-only by design; the refusal prefix itself stays
# multilingual (REFUSAL_RESPONSES, D-077).
_STATUTE_REASON_RE = re.compile(r"query names statute '([^']+)' which is not the indexed corpus")
_NO_SESSION_REASONS = (
    "document route requested without a session id",
    "no session document chunks matched",
)


def _refusal_reason_sentence(evidence: RetrievedEvidence) -> str | None:
    """User-facing reason sentence for an insufficient-evidence refusal.

    Maps the strongest retrieval failure reason to a code-authored English
    sentence, or None when no reason applies (the refusal line stays
    unchanged). ``evidence.reasons`` entries are constants produced by the
    retrieval layer; this function never passes them through verbatim.
    """
    reasons = evidence.reasons or []
    for reason in reasons:
        match = _STATUTE_REASON_RE.search(reason)
        if match is not None:
            statute = re.sub(r"[^A-Za-z ]", "", match.group(1)).strip()
            if evidence.indexed_acts:
                # Truthful corpus boundary: name the acts actually indexed
                # (retrieval-supplied) rather than a hardcoded corpus name,
                # so the sentence stays correct when the corpus changes.
                names = ", ".join(evidence.indexed_acts)
                return (
                    f"The indexed corpus ({names}) does not cover {statute}; this "
                    f"assistant answers from {names} and your uploaded documents only."
                )
            return (
                f"The BNS corpus does not cover {statute}; this assistant answers from "
                "the Bharatiya Nyaya Sanhita and your uploaded documents only."
            )
    for reason in reasons:
        if any(marker in reason for marker in _NO_SESSION_REASONS):
            return "No documents are uploaded in this session. Upload a document and ask again."
    for reason in reasons:
        if "below threshold" in reason:
            return "The retrieved material does not confidently match this question."
    for reason in reasons:
        if "no chunks matched" in reason or "not present in the indexed corpus" in reason:
            return "No material in the indexed corpus matches this question."
    return None


def _refusal_for(language: LanguageCode | None) -> str:
    """Code-controlled refusal in the answer language (never model-made)."""
    return REFUSAL_RESPONSES[language or _ENGLISH]


#: Code-authored reason for a MODEL-emitted refusal (retrieval succeeded but
#: the grounded model found no answer in the evidence — e.g. a procedural
#: question such as bail, which lives in the BNSS, not the BNS corpus).
_MODEL_REFUSAL_REASON = (
    "The retrieved material does not contain the answer to this question; "
    "it may be governed by a different statute or by your uploaded documents."
)


def _refusal_with_reason(refusal_text: str, reason: str | None) -> str:
    """Refusal line plus the reason sentence — both code-authored."""
    if reason is None:
        return refusal_text
    return f"{refusal_text} {reason}"


class EmptyGenerationError(AppError):
    """The provider returned no content for a sufficient-evidence question."""

    status_code = 503
    code = "LLM_EMPTY_RESPONSE"


@dataclass(slots=True)
class GenerationOutcome:
    """Result of one grounded generation call."""

    answer: str
    refused: bool
    citations: CitationCheck = field(default_factory=CitationCheck)
    sources: list[dict[str, object]] = field(default_factory=list)
    model: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    #: Code-authored user-facing reason sentence appended to the refusal
    #: answer ("The BNS corpus does not cover ..."). None on grounded
    #: answers and on refusals with no identifiable cause (the bare
    #: specification line rides alone).
    refusal_reason: str | None = None


def _is_refusal_text(answer: str) -> bool:
    """True when the model produced the specification refusal.

    Matches the refusal in ANY supported language (the model may echo the
    translated refusal text, D-077) — the outcome is then normalized to
    the code-controlled refusal of the answer language. The refusal may
    be prefaced with a short hedge ("...therefore: I don't know based on
    the available source material."), so a trailing match counts too.
    """
    stripped = answer.strip()
    for refusal in REFUSAL_RESPONSES.values():
        if stripped == refusal or stripped.endswith(refusal):
            return True
    return False


class GenerationService:
    """Evidence-grounded answering with code-level citation enforcement."""

    def __init__(self, provider: LLMProvider, *, max_attempts: int = 3) -> None:
        self._provider = provider
        self._max_attempts = max_attempts

    async def answer(
        self,
        question: str,
        evidence: RetrievedEvidence,
        history: list[ChatMessage] | None = None,
        *,
        answer_language: LanguageCode | None = None,
    ) -> GenerationOutcome:
        """Generate a grounded, citation-validated answer (or refusal).

        The confidence gate (ARCHITECTURE §15) runs before any LLM call:
        insufficient evidence produces the specification refusal without the
        model seeing the question. Generated answers are sanitized by the
        citation guard; if the guard removed sentences, one regeneration
        attempt is made before accepting the sanitized text.

        ``answer_language`` (D-077) selects the answer language; None means
        English (the pre-multilingual contract, byte-identical prompt). The
        refusal and the language instruction are code-controlled, so the
        language can never weaken grounding, citations, or refusal.
        """
        refusal_text = _refusal_for(answer_language)
        if not evidence.sufficient or (not evidence.results and not evidence.document_hits):
            reason = _refusal_reason_sentence(evidence)
            logger.info(
                "refusing: insufficient evidence",
                extra={
                    "event": "generation_refusal",
                    "reason": "insufficient_evidence",
                    "retrieval_reasons": list(evidence.reasons[:5]),
                    "confidence": round(evidence.confidence, 4),
                },
            )
            REFUSALS.inc()
            return GenerationOutcome(
                answer=_refusal_with_reason(refusal_text, reason),
                refused=True,
                refusal_reason=reason,
            )

        instruction = (
            answer_instruction(answer_language)
            if answer_language is not None and answer_language != _ENGLISH
            else None
        )
        request = build_generation_request(
            question,
            evidence.results,
            history,
            document_hits=evidence.document_hits,
            answer_language_instruction=instruction,
        )
        # Concrete citation-label forms for the regeneration instruction —
        # the same labels the evidence blocks carry (prompt.py).
        labels = list(
            dict.fromkeys(
                [f"[{s.chunk.act_short} s.{s.chunk.section_number}]" for s in evidence.results]
                + [f"[Document {h.document_id}]" for h in evidence.document_hits or []]
            )
        )
        label_examples = ", ".join(labels[:3])
        check = CitationCheck()
        answer = ""
        model: str | None = None
        prompt_tokens: int | None = None
        completion_tokens: int | None = None
        saw_text = False
        contaminated = False
        # Latest fully-validated answer (non-empty, cited, not refused):
        # a later regeneration that refuses must not discard it.
        answer_prev: str = ""
        check_prev: CitationCheck | None = None
        for attempt in range(self._max_attempts):
            try:
                result = await self._provider.generate(request)
            except Exception:
                # A failed REGENERATION (provider 429/timeout/exception)
                # must not destroy an already-valid sanitized answer from an
                # earlier attempt — observed live: guard triggered a regen,
                # the rate-limited provider raised, and the user saw "chat
                # service unavailable" instead of the good answer. Preserve
                # only a fully valid answer (non-empty, cited, not refused);
                # with nothing valid to preserve the error propagates.
                if (
                    saw_text
                    and answer.strip()
                    and (check.valid_citations or check.cited_document_ids)
                ):
                    logger.warning(
                        "regeneration failed; preserving earlier validated answer",
                        extra={
                            "event": "generation_regeneration_failed_answer_preserved",
                            "attempt": attempt + 1,
                        },
                    )
                    break
                raise
            model = result.model or model
            prompt_tokens = (result.prompt_tokens or 0) + (prompt_tokens or 0) or None
            completion_tokens = (result.completion_tokens or 0) + (completion_tokens or 0) or None
            text = sanitize_answer_text(result.text)
            if not text.strip():
                # An empty completion is a provider failure, not an answer.
                logger.info(
                    "provider returned empty response",
                    extra={"event": "generation_empty_response", "attempt": attempt + 1},
                )
                continue
            # Prompt/reasoning echo defense (defense in depth on top of the
            # provider-layer sanitizer): a "content" field that echoes the
            # grounding prompt, evidence blocks or the internal regeneration
            # instruction is reasoning leakage, never an answer. Retry once;
            # if every attempt is contaminated the outcome is the code-level
            # refusal — contaminated text never reaches validation or SSE.
            if is_prompt_echo(text, request.messages):
                contaminated = True
                logger.warning(
                    "answer looked like a prompt/reasoning echo; retrying",
                    extra={"event": "generation_prompt_echo", "attempt": attempt + 1},
                )
                continue
            saw_text = True
            answer, check = validate_citations(
                text, evidence.results, document_hits=evidence.document_hits
            )
            if _is_refusal_text(answer):
                # The model itself refused. Normalize to the code-level
                # refusal — UNLESS a regeneration is refusing after an
                # earlier attempt already produced a valid, cited answer:
                # the guard stripped sentences on attempt 1, the regen
                # prompt asked the model to continue, and a literal model
                # refusal at that point (observed live: the exact
                # specification string) must not discard the preserved
                # answer the user would otherwise have received. Preserve
                # only a fully valid answer (non-empty, cited, not
                # refused); otherwise the refusal is honest.
                if (
                    answer_prev.strip()
                    and check_prev is not None
                    and (check_prev.valid_citations or check_prev.cited_document_ids)
                ):
                    logger.warning(
                        "regeneration refused; preserving earlier validated answer",
                        extra={
                            "event": "generation_regenerated_refusal_answer_preserved",
                            "attempt": attempt + 1,
                        },
                    )
                    answer = answer_prev
                    check = check_prev
                    break
                # A first-attempt refusal, or a regen refusal with nothing
                # valid preserved: refused=true and REFUSALS stay truthful.
                logger.info(
                    "model emitted refusal text; normalizing",
                    extra={"event": "generation_refusal", "reason": "model_emitted"},
                )
                REFUSALS.inc()
                return GenerationOutcome(
                    answer=_refusal_with_reason(refusal_text, _MODEL_REFUSAL_REASON),
                    refused=True,
                    citations=check,
                    refusal_reason=_MODEL_REFUSAL_REASON,
                    model=model,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                )
            if not check.removed_sentences:
                break
            # Record the current sanitized (partially valid) answer as the
            # preservation candidate before regenerating.
            answer_prev, check_prev = answer, check
            logger.info(
                "citation guard removed sentences; regenerating",
                extra={
                    "event": "citation_guard_regeneration",
                    "attempt": attempt + 1,
                    "removed": len(check.removed_sentences),
                },
            )
            # Regeneration gets the same evidence and rules; append the
            # sanitized prefix as the assistant context so the model does not
            # repeat the removed claim. The exact citation-label forms are
            # restated concretely: some models honor "as instructed" only on
            # the first turn and drop the labels on regeneration, which would
            # strip every sentence again and turn a good answer into a refusal.
            request = GenerationRequest(
                messages=[
                    *request.messages,
                    ChatMessage(role=MessageRole.ASSISTANT, content=answer),
                    ChatMessage(
                        role=MessageRole.USER,
                        content=(
                            "Continue the answer using ONLY the evidence above. "
                            "Do not repeat removed statements; cite every legal "
                            "claim in the exact inline form of the evidence "
                            f"labels, e.g. {label_examples}."
                        ),
                    ),
                ]
            )

        if not saw_text:
            if contaminated:
                # Every attempt echoed the prompt/reasoning: fail closed with
                # the code-controlled refusal. Never stream contaminated text.
                logger.warning(
                    "refusing: every attempt echoed the prompt or reasoning",
                    extra={"event": "generation_refusal", "reason": "prompt_echo"},
                )
                REFUSALS.inc()
                return GenerationOutcome(
                    answer=refusal_text,
                    refused=True,
                    model=model,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens,
                )
            logger.warning("provider produced no content across attempts")
            raise EmptyGenerationError("The generation provider returned an empty response.")

        if not answer.strip():
            # Every sentence was stripped by the guard: nothing grounded
            # survived, so the honest outcome is the specification refusal.
            logger.info(
                "refusing: no grounded sentence survived validation",
                extra={"event": "generation_refusal", "reason": "empty_answer_after_validation"},
            )
            REFUSALS.inc()
            return GenerationOutcome(
                answer=refusal_text,
                refused=True,
                model=model,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
            )

        if not check.valid_citations and not check.cited_document_ids:
            # A non-empty answer with ZERO citations cannot be a grounded
            # legal answer (every legal claim must carry a citation). A
            # model that "complies" with "don't cite the answer" produces
            # exactly this shape — refuse rather than emit uncited law.
            logger.info(
                "refusing: answer carries no citations",
                extra={"event": "generation_refusal", "reason": "no_citations_in_answer"},
            )
            REFUSALS.inc()
            return GenerationOutcome(
                answer=refusal_text,
                refused=True,
                model=model,
                prompt_tokens=prompt_tokens,
                completion_tokens=completion_tokens,
            )

        sources: list[dict[str, object]] = build_sources(evidence.results, check.valid_citations)
        # Document sources are distinguished from statutory authority
        # (A5-012) and emitted only for documents the answer actually cites.
        cited_documents = set(check.cited_document_ids)
        document_sources: list[dict[str, object]] = [
            {
                "source_type": "user_document",
                "citation": (
                    f"[Document {hit.document_id} p.{hit.page_start}]"
                    if hit.page_start
                    else f"[Document {hit.document_id}]"
                ),
                "document_id": hit.document_id,
                "chunk_id": hit.chunk_id,
                "text": hit.text,
                "page_start": hit.page_start,
                "page_end": hit.page_end,
                "source_uri": hit.source_uri,
            }
            for hit in evidence.document_hits
            if hit.document_id in cited_documents
        ]
        for source in sources:
            source["source_type"] = "statute"
        logger.info(
            "generation complete",
            extra={
                "event": "generation_complete",
                "answer_length": len(answer),
                "citations_valid": len(check.valid_citations),
                "citations_invalid": len(check.invalid_citations),
                "citations_irrelevant": len(check.irrelevant_citations),
                "documents_cited": len(cited_documents),
                "model": model,
            },
        )
        return GenerationOutcome(
            answer=answer,
            refused=False,
            citations=check,
            sources=[*sources, *document_sources],
            model=model,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
        )
