import { expect, test } from "@playwright/test";

/**
 * Final release-check interactions (real Chromium against the live docker
 * stack): conversations, citation chips -> source drawer, document upload
 * progress, forms panel flows, theme, mobile viewport, keyboard access.
 *
 * Run: npx playwright test --config e2e/playwright.config.ts
 * Prereq: docker compose up (frontend on 127.0.0.1:3000, API on :8000).
 */

const FRONTEND = process.env.E2E_BASE_URL ?? "http://localhost:3000";

test.describe.serial("release check", () => {
  test("citation chip opens the source drawer with the statutory text", async ({ page }) => {
    await page.goto(FRONTEND);
    const input = page.getByPlaceholder("Ask a legal question…");
    await input.fill("What does section 304 of the BNS say about snatching?");
    await input.press("Enter");

    // Wait for the streamed answer, then click the first citation chip.
    const chip = page.getByRole("button", { name: /BNS s\.?\s*304/i }).first();
    await expect(chip).toBeVisible({ timeout: 120_000 });
    await chip.click();

    // The source drawer shows the retrieved chunk verbatim + page number.
    const drawer = page.getByRole("dialog", { name: /Source for/i });
    await expect(drawer).toBeVisible();
    await expect(drawer).toContainText(/snatching/i);
    await expect(drawer).toContainText(/page/i, { ignoreCase: true });
  });

  test("conversation: create, rename, delete", async ({ page }) => {
    await page.goto(FRONTEND);
    const input = page.getByPlaceholder("Ask a legal question…");
    await input.fill("What is section 103 of the BNS?");
    await input.press("Enter");
    await expect
      .poll(async () => page.getByRole("log").textContent(), { timeout: 120_000 })
      .toContain("murder", { ignoreCase: true });

    // The conversation is named from the first user message.
    const list = page.getByRole("navigation", { name: "Conversations" });
    await expect(list).toContainText(/section 103/i);

    // New conversation button exists and switches to an empty state.
    await page.getByRole("button", { name: /new conversation/i }).click();
    await expect(page.getByPlaceholder("Ask a legal question…")).toBeVisible();

    // Rename the conversation via its inline edit affordance.
    await list.getByRole("button", { name: /^Rename /i }).first().click();
    const renameInput = list.getByRole("textbox");
    await renameInput.fill("Renamed release check");
    await renameInput.press("Enter");
    await expect(list).toContainText("Renamed release check");

    // Delete: two-step confirm per conversation, until the list is empty.
    for (let guard = 0; guard < 10; guard++) {
      const first = list.getByRole("button", { name: /^Delete /i }).first();
      if ((await list.getByRole("button", { name: /^Delete /i }).count()) === 0) break;
      await first.click(); // arm
      await list.getByRole("button", { name: /^Confirm delete /i }).first().click();
    }
    await expect(list.getByRole("button", { name: /^Delete /i })).toHaveCount(0);
  });

  test("forms panel: search, preview, download", async ({ page }) => {
    await page.goto(FRONTEND);
    await page.getByRole("tab", { name: "Forms" }).click();

    const search = page.getByPlaceholder("Search by title or number…");
    await search.fill("bail");
    // Title search is debounced; wait for the filtered list to settle.
    await expect
      .poll(async () => page.getByRole("list").last().textContent(), { timeout: 10_000 })
      .toContain("BAIL");

    // Preview opens a modal with the form's PDF (object URL).
    await page.getByRole("button", { name: /preview/i }).first().click();
    const dialog = page.getByRole("dialog");
    await expect(dialog).toBeVisible();
    await expect(dialog.locator("iframe, object, embed").first()).toBeVisible();
    await page.getByRole("button", { name: /close/i }).first().click();
    await expect(dialog).toBeHidden();

    // Single download is an <a download> link to the form PDF.
    const download = page.waitForEvent("download", { timeout: 30_000 });
    await page.getByRole("list").last().getByRole("link", { name: /^Download$/i }).first().click();
    expect((await download).suggestedFilename()).toMatch(/^FORM-\d+_.+\.pdf$/);
  });

  test("document upload shows progress and reaches ready", async ({ page }) => {
    await page.goto(FRONTEND);
    // A real one-page PDF fixture (generated by the backend test helper).
    const { readFile } = await import("node:fs/promises");
    await page.setInputFiles('input[type="file"]', {
      name: "receipt.pdf",
      mimeType: "application/pdf",
      buffer: await readFile("/tmp/e2e_receipt.pdf"),
    });
    // Processing stages are announced, then the document is queryable.
    await expect
      .poll(
        async () => page.getByRole("complementary", { name: "Uploaded documents" }).textContent(),
        { timeout: 120_000 },
      )
      .toContain("receipt.pdf");
    await expect(page.getByRole("complementary", { name: "Uploaded documents" })).toContainText(
      /ready/i,
    );
  });

  test("theme toggle switches dark and light mode", async ({ page }) => {
    await page.goto(FRONTEND);
    const toggle = page.getByRole("button", { name: /switch to (dark|light) mode/i });
    const before = await page.evaluate(() => document.documentElement.classList.contains("dark"));
    await toggle.click();
    await expect(page.locator("html")).toHaveClass(before ? /^((?!dark).)*$/ : /dark/);
    await toggle.click();
    await expect(page.locator("html")).toHaveClass(before ? /dark/ : /^((?!dark).)*$/);
  });

  test("mobile viewport renders the chat with a working menu", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(FRONTEND);
    await expect(page.getByPlaceholder("Ask a legal question…")).toBeVisible();
    await page.getByRole("button", { name: "Toggle conversations sidebar" }).click();
    await expect(page.getByRole("navigation", { name: "Conversations" })).toBeVisible();
  });

  test("keyboard navigation reaches the chat input with a visible focus", async ({ page }) => {
    await page.goto(FRONTEND);
    // Tab from the body into the app: focus lands on interactive elements
    // and the chat input is reachable by keyboard alone.
    for (let i = 0; i < 20; i++) {
      await page.keyboard.press("Tab");
      if (await page.evaluate(() => document.activeElement?.matches("textarea, input[type=text]"))) {
        break;
      }
    }
    const focused = page.locator(":focus");
    await expect(focused).toBeVisible();
  });
});
